workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: ios_credentials # This should be set in Codemagic UI
    environment:
      ios_signing:
        distribution_type: app_store  # Set to ad_hoc for internal testing
        bundle_identifier: com.yourname.edgeai  # Change to your actual Bundle ID
      vars:
        XCODE_WORKSPACE: "MyTFLiteApp.xcworkspace"  # If using workspaces
        XCODE_SCHEME: "MyTFLiteApp"
        APP_STORE_APP_ID: 123456789  # Change this to your real App Store ID
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - TestGroupName  # Replace with your actual TestFlight Group
        submit_to_app_store: false
